name: Compile Laravel Assets

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, pdo_mysql, gd
        tools: composer:v2

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Node Dependencies
      run: npm install

    - name: Compile Assets
      run: npm run build

  deploy:
    needs: compile-assets # Only run after assets compilation is successful.
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        HOST: 18.178.29.243
        USER: ec2-user # Usually 'ubuntu' or 'ec2-user' depending on the AMI you've chosen.
      run: |
        echo "$PRIVATE_KEY" > deploy_key
        chmod 600 deploy_key
        scp -i deploy_key -o StrictHostKeyChecking=no -r ./public/build $USER@$HOST:/path/to/your/laravel/app/on/ec2/public/
        rm -f deploy_key