name: Compile Laravel Assets

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo_mysql, gd
        tools: composer:v2

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Node Dependencies
      run: npm install

    - name: Compile Assets
      run: npm run build
    
    - name: List files in public directory after build
      run: ls -la public/

    - name: Archive build output
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: ./

  deploy:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: build-artifact

    - name: List all files and directories before scp
      run: ls -la
      
    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        HOST: 18.178.29.243
        USER: ec2-user
      run: |
        echo "$PRIVATE_KEY" > deploy_key
        chmod 600 deploy_key
        scp -i deploy_key -o StrictHostKeyChecking=no -r ./* $USER@$HOST:/var/www/html/shokuka
        rm -f deploy_key 
